# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_status', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='red', max_length=10)),
                ('manual_status', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='red', max_length=10)),
                ('last_status_code', models.IntegerField(default=0)),
                ('last_check_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(default='')),
            ],
        ),
    ]
