# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='display_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
