# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0002_service_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
