# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0002_auto_20160428_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
