# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0003_service_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='manual_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
