# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0003_auto_20160518_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='auto_status',
            field=models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='manual_status',
            field=models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='green', max_length=10),
        ),
    ]
