# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_status', '0004_auto_20160430_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='auto_status',
            field=models.BooleanField(default=False),
        ),
    ]
